// Lista completa de países con códigos ISO y nacionalidades
export const COUNTRIES = [
  { code: "ESP", name: "España", nameEn: "Spain", nationality: "Española", nationalityEn: "Spanish" },
  { code: "AFG", name: "Afganistán", nameEn: "Afghanistan", nationality: "Afgana", nationalityEn: "Afghan" },
  { code: "ALB", name: "Albania", nameEn: "Albania", nationality: "Albanesa", nationalityEn: "Albanian" },
  { code: "DEU", name: "Alemania", nameEn: "Germany", nationality: "Alemana", nationalityEn: "German" },
  { code: "AND", name: "Andorra", nameEn: "Andorra", nationality: "Andorrana", nationalityEn: "Andorran" },
  { code: "AGO", name: "Angola", nameEn: "Angola", nationality: "Angoleña", nationalityEn: "Angolan" },
  { code: "SAU", name: "Arabia Saudita", nameEn: "Saudi Arabia", nationality: "Saudí", nationalityEn: "Saudi" },
  { code: "DZA", name: "Argelia", nameEn: "Algeria", nationality: "Argelina", nationalityEn: "Algerian" },
  { code: "ARG", name: "Argentina", nameEn: "Argentina", nationality: "Argentina", nationalityEn: "Argentine" },
  { code: "ARM", name: "Armenia", nameEn: "Armenia", nationality: "Armenia", nationalityEn: "Armenian" },
  { code: "AUS", name: "Australia", nameEn: "Australia", nationality: "Australiana", nationalityEn: "Australian" },
  { code: "AUT", name: "Austria", nameEn: "Austria", nationality: "Austriaca", nationalityEn: "Austrian" },
  { code: "AZE", name: "Azerbaiyán", nameEn: "Azerbaijan", nationality: "Azerbaiyana", nationalityEn: "Azerbaijani" },
  { code: "BHS", name: "Bahamas", nameEn: "Bahamas", nationality: "Bahameña", nationalityEn: "Bahamian" },
  { code: "BGD", name: "Bangladés", nameEn: "Bangladesh", nationality: "Bangladesí", nationalityEn: "Bangladeshi" },
  { code: "BRB", name: "Barbados", nameEn: "Barbados", nationality: "Barbadense", nationalityEn: "Barbadian" },
  { code: "BHR", name: "Baréin", nameEn: "Bahrain", nationality: "Bareiní", nationalityEn: "Bahraini" },
  { code: "BEL", name: "Bélgica", nameEn: "Belgium", nationality: "Belga", nationalityEn: "Belgian" },
  { code: "BLZ", name: "Belice", nameEn: "Belize", nationality: "Beliceña", nationalityEn: "Belizean" },
  { code: "BEN", name: "Benín", nameEn: "Benin", nationality: "Beninesa", nationalityEn: "Beninese" },
  { code: "BLR", name: "Bielorrusia", nameEn: "Belarus", nationality: "Bielorrusa", nationalityEn: "Belarusian" },
  { code: "BOL", name: "Bolivia", nameEn: "Bolivia", nationality: "Boliviana", nationalityEn: "Bolivian" },
  { code: "BIH", name: "Bosnia y Herzegovina", nameEn: "Bosnia and Herzegovina", nationality: "Bosnia", nationalityEn: "Bosnian" },
  { code: "BWA", name: "Botsuana", nameEn: "Botswana", nationality: "Botsuanesa", nationalityEn: "Botswanan" },
  { code: "BRA", name: "Brasil", nameEn: "Brazil", nationality: "Brasileña", nationalityEn: "Brazilian" },
  { code: "BRN", name: "Brunéi", nameEn: "Brunei", nationality: "Bruneana", nationalityEn: "Bruneian" },
  { code: "BGR", name: "Bulgaria", nameEn: "Bulgaria", nationality: "Búlgara", nationalityEn: "Bulgarian" },
  { code: "BFA", name: "Burkina Faso", nameEn: "Burkina Faso", nationality: "Burkinesa", nationalityEn: "Burkinabe" },
  { code: "BDI", name: "Burundi", nameEn: "Burundi", nationality: "Burundesa", nationalityEn: "Burundian" },
  { code: "BTN", name: "Bután", nameEn: "Bhutan", nationality: "Butanesa", nationalityEn: "Bhutanese" },
  { code: "CPV", name: "Cabo Verde", nameEn: "Cape Verde", nationality: "Caboverdiana", nationalityEn: "Cape Verdean" },
  { code: "KHM", name: "Camboya", nameEn: "Cambodia", nationality: "Camboyana", nationalityEn: "Cambodian" },
  { code: "CMR", name: "Camerún", nameEn: "Cameroon", nationality: "Camerunesa", nationalityEn: "Cameroonian" },
  { code: "CAN", name: "Canadá", nameEn: "Canada", nationality: "Canadiense", nationalityEn: "Canadian" },
  { code: "QAT", name: "Catar", nameEn: "Qatar", nationality: "Catarí", nationalityEn: "Qatari" },
  { code: "TCD", name: "Chad", nameEn: "Chad", nationality: "Chadiana", nationalityEn: "Chadian" },
  { code: "CHL", name: "Chile", nameEn: "Chile", nationality: "Chilena", nationalityEn: "Chilean" },
  { code: "CHN", name: "China", nameEn: "China", nationality: "China", nationalityEn: "Chinese" },
  { code: "CYP", name: "Chipre", nameEn: "Cyprus", nationality: "Chipriota", nationalityEn: "Cypriot" },
  { code: "COL", name: "Colombia", nameEn: "Colombia", nationality: "Colombiana", nationalityEn: "Colombian" },
  { code: "COM", name: "Comoras", nameEn: "Comoros", nationality: "Comorense", nationalityEn: "Comoran" },
  { code: "COG", name: "Congo", nameEn: "Congo", nationality: "Congoleña", nationalityEn: "Congolese" },
  { code: "PRK", name: "Corea del Norte", nameEn: "North Korea", nationality: "Norcoreana", nationalityEn: "North Korean" },
  { code: "KOR", name: "Corea del Sur", nameEn: "South Korea", nationality: "Surcoreana", nationalityEn: "South Korean" },
  { code: "CIV", name: "Costa de Marfil", nameEn: "Ivory Coast", nationality: "Marfileña", nationalityEn: "Ivorian" },
  { code: "CRI", name: "Costa Rica", nameEn: "Costa Rica", nationality: "Costarricense", nationalityEn: "Costa Rican" },
  { code: "HRV", name: "Croacia", nameEn: "Croatia", nationality: "Croata", nationalityEn: "Croatian" },
  { code: "CUB", name: "Cuba", nameEn: "Cuba", nationality: "Cubana", nationalityEn: "Cuban" },
  { code: "DNK", name: "Dinamarca", nameEn: "Denmark", nationality: "Danesa", nationalityEn: "Danish" },
  { code: "DMA", name: "Dominica", nameEn: "Dominica", nationality: "Dominiqués", nationalityEn: "Dominican" },
  { code: "ECU", name: "Ecuador", nameEn: "Ecuador", nationality: "Ecuatoriana", nationalityEn: "Ecuadorian" },
  { code: "EGY", name: "Egipto", nameEn: "Egypt", nationality: "Egipcia", nationalityEn: "Egyptian" },
  { code: "SLV", name: "El Salvador", nameEn: "El Salvador", nationality: "Salvadoreña", nationalityEn: "Salvadoran" },
  { code: "ARE", name: "Emiratos Árabes Unidos", nameEn: "United Arab Emirates", nationality: "Emiratí", nationalityEn: "Emirati" },
  { code: "ERI", name: "Eritrea", nameEn: "Eritrea", nationality: "Eritrea", nationalityEn: "Eritrean" },
  { code: "SVK", name: "Eslovaquia", nameEn: "Slovakia", nationality: "Eslovaca", nationalityEn: "Slovak" },
  { code: "SVN", name: "Eslovenia", nameEn: "Slovenia", nationality: "Eslovena", nationalityEn: "Slovenian" },
  { code: "USA", name: "Estados Unidos", nameEn: "United States", nationality: "Estadounidense", nationalityEn: "American" },
  { code: "EST", name: "Estonia", nameEn: "Estonia", nationality: "Estonia", nationalityEn: "Estonian" },
  { code: "ETH", name: "Etiopía", nameEn: "Ethiopia", nationality: "Etíope", nationalityEn: "Ethiopian" },
  { code: "PHL", name: "Filipinas", nameEn: "Philippines", nationality: "Filipina", nationalityEn: "Filipino" },
  { code: "FIN", name: "Finlandia", nameEn: "Finland", nationality: "Finlandesa", nationalityEn: "Finnish" },
  { code: "FJI", name: "Fiyi", nameEn: "Fiji", nationality: "Fiyiana", nationalityEn: "Fijian" },
  { code: "FRA", name: "Francia", nameEn: "France", nationality: "Francesa", nationalityEn: "French" },
  { code: "GAB", name: "Gabón", nameEn: "Gabon", nationality: "Gabonesa", nationalityEn: "Gabonese" },
  { code: "GMB", name: "Gambia", nameEn: "Gambia", nationality: "Gambiana", nationalityEn: "Gambian" },
  { code: "GEO", name: "Georgia", nameEn: "Georgia", nationality: "Georgiana", nationalityEn: "Georgian" },
  { code: "GHA", name: "Ghana", nameEn: "Ghana", nationality: "Ghanesa", nationalityEn: "Ghanaian" },
  { code: "GRC", name: "Grecia", nameEn: "Greece", nationality: "Griega", nationalityEn: "Greek" },
  { code: "GRD", name: "Granada", nameEn: "Grenada", nationality: "Granadina", nationalityEn: "Grenadian" },
  { code: "GTM", name: "Guatemala", nameEn: "Guatemala", nationality: "Guatemalteca", nationalityEn: "Guatemalan" },
  { code: "GIN", name: "Guinea", nameEn: "Guinea", nationality: "Guineana", nationalityEn: "Guinean" },
  { code: "GNB", name: "Guinea-Bisáu", nameEn: "Guinea-Bissau", nationality: "Guineana", nationalityEn: "Bissau-Guinean" },
  { code: "GNQ", name: "Guinea Ecuatorial", nameEn: "Equatorial Guinea", nationality: "Ecuatoguineana", nationalityEn: "Equatorial Guinean" },
  { code: "GUY", name: "Guyana", nameEn: "Guyana", nationality: "Guyanesa", nationalityEn: "Guyanese" },
  { code: "HTI", name: "Haití", nameEn: "Haiti", nationality: "Haitiana", nationalityEn: "Haitian" },
  { code: "HND", name: "Honduras", nameEn: "Honduras", nationality: "Hondureña", nationalityEn: "Honduran" },
  { code: "HUN", name: "Hungría", nameEn: "Hungary", nationality: "Húngara", nationalityEn: "Hungarian" },
  { code: "IND", name: "India", nameEn: "India", nationality: "India", nationalityEn: "Indian" },
  { code: "IDN", name: "Indonesia", nameEn: "Indonesia", nationality: "Indonesia", nationalityEn: "Indonesian" },
  { code: "IRQ", name: "Irak", nameEn: "Iraq", nationality: "Iraquí", nationalityEn: "Iraqi" },
  { code: "IRN", name: "Irán", nameEn: "Iran", nationality: "Iraní", nationalityEn: "Iranian" },
  { code: "IRL", name: "Irlanda", nameEn: "Ireland", nationality: "Irlandesa", nationalityEn: "Irish" },
  { code: "ISL", name: "Islandia", nameEn: "Iceland", nationality: "Islandesa", nationalityEn: "Icelandic" },
  { code: "ISR", name: "Israel", nameEn: "Israel", nationality: "Israelí", nationalityEn: "Israeli" },
  { code: "ITA", name: "Italia", nameEn: "Italy", nationality: "Italiana", nationalityEn: "Italian" },
  { code: "JAM", name: "Jamaica", nameEn: "Jamaica", nationality: "Jamaicana", nationalityEn: "Jamaican" },
  { code: "JPN", name: "Japón", nameEn: "Japan", nationality: "Japonesa", nationalityEn: "Japanese" },
  { code: "JOR", name: "Jordania", nameEn: "Jordan", nationality: "Jordana", nationalityEn: "Jordanian" },
  { code: "KAZ", name: "Kazajistán", nameEn: "Kazakhstan", nationality: "Kazaja", nationalityEn: "Kazakhstani" },
  { code: "KEN", name: "Kenia", nameEn: "Kenya", nationality: "Keniana", nationalityEn: "Kenyan" },
  { code: "KGZ", name: "Kirguistán", nameEn: "Kyrgyzstan", nationality: "Kirguisa", nationalityEn: "Kyrgyzstani" },
  { code: "KIR", name: "Kiribati", nameEn: "Kiribati", nationality: "Kiribatiana", nationalityEn: "I-Kiribati" },
  { code: "KWT", name: "Kuwait", nameEn: "Kuwait", nationality: "Kuwaití", nationalityEn: "Kuwaiti" },
  { code: "LAO", name: "Laos", nameEn: "Laos", nationality: "Laosiana", nationalityEn: "Laotian" },
  { code: "LSO", name: "Lesoto", nameEn: "Lesotho", nationality: "Lesotense", nationalityEn: "Basotho" },
  { code: "LVA", name: "Letonia", nameEn: "Latvia", nationality: "Letona", nationalityEn: "Latvian" },
  { code: "LBN", name: "Líbano", nameEn: "Lebanon", nationality: "Libanesa", nationalityEn: "Lebanese" },
  { code: "LBR", name: "Liberia", nameEn: "Liberia", nationality: "Liberiana", nationalityEn: "Liberian" },
  { code: "LBY", name: "Libia", nameEn: "Libya", nationality: "Libia", nationalityEn: "Libyan" },
  { code: "LIE", name: "Liechtenstein", nameEn: "Liechtenstein", nationality: "Liechtensteiniana", nationalityEn: "Liechtensteiner" },
  { code: "LTU", name: "Lituania", nameEn: "Lithuania", nationality: "Lituana", nationalityEn: "Lithuanian" },
  { code: "LUX", name: "Luxemburgo", nameEn: "Luxembourg", nationality: "Luxemburguesa", nationalityEn: "Luxembourgish" },
  { code: "MKD", name: "Macedonia del Norte", nameEn: "North Macedonia", nationality: "Macedonia", nationalityEn: "Macedonian" },
  { code: "MDG", name: "Madagascar", nameEn: "Madagascar", nationality: "Malgache", nationalityEn: "Malagasy" },
  { code: "MYS", name: "Malasia", nameEn: "Malaysia", nationality: "Malasia", nationalityEn: "Malaysian" },
  { code: "MWI", name: "Malaui", nameEn: "Malawi", nationality: "Malauí", nationalityEn: "Malawian" },
  { code: "MDV", name: "Maldivas", nameEn: "Maldives", nationality: "Maldiva", nationalityEn: "Maldivian" },
  { code: "MLI", name: "Malí", nameEn: "Mali", nationality: "Maliense", nationalityEn: "Malian" },
  { code: "MLT", name: "Malta", nameEn: "Malta", nationality: "Maltesa", nationalityEn: "Maltese" },
  { code: "MAR", name: "Marruecos", nameEn: "Morocco", nationality: "Marroquí", nationalityEn: "Moroccan" },
  { code: "MUS", name: "Mauricio", nameEn: "Mauritius", nationality: "Mauriciana", nationalityEn: "Mauritian" },
  { code: "MRT", name: "Mauritania", nameEn: "Mauritania", nationality: "Mauritana", nationalityEn: "Mauritanian" },
  { code: "MEX", name: "México", nameEn: "Mexico", nationality: "Mexicana", nationalityEn: "Mexican" },
  { code: "FSM", name: "Micronesia", nameEn: "Micronesia", nationality: "Micronesia", nationalityEn: "Micronesian" },
  { code: "MDA", name: "Moldavia", nameEn: "Moldova", nationality: "Moldava", nationalityEn: "Moldovan" },
  { code: "MCO", name: "Mónaco", nameEn: "Monaco", nationality: "Monegasca", nationalityEn: "Monégasque" },
  { code: "MNG", name: "Mongolia", nameEn: "Mongolia", nationality: "Mongola", nationalityEn: "Mongolian" },
  { code: "MNE", name: "Montenegro", nameEn: "Montenegro", nationality: "Montenegrina", nationalityEn: "Montenegrin" },
  { code: "MOZ", name: "Mozambique", nameEn: "Mozambique", nationality: "Mozambiqueña", nationalityEn: "Mozambican" },
  { code: "MMR", name: "Birmania", nameEn: "Myanmar", nationality: "Birmana", nationalityEn: "Burmese" },
  { code: "NAM", name: "Namibia", nameEn: "Namibia", nationality: "Namibia", nationalityEn: "Namibian" },
  { code: "NRU", name: "Nauru", nameEn: "Nauru", nationality: "Nauruana", nationalityEn: "Nauruan" },
  { code: "NPL", name: "Nepal", nameEn: "Nepal", nationality: "Nepalí", nationalityEn: "Nepalese" },
  { code: "NIC", name: "Nicaragua", nameEn: "Nicaragua", nationality: "Nicaragüense", nationalityEn: "Nicaraguan" },
  { code: "NER", name: "Níger", nameEn: "Niger", nationality: "Nigerina", nationalityEn: "Nigerien" },
  { code: "NGA", name: "Nigeria", nameEn: "Nigeria", nationality: "Nigeriana", nationalityEn: "Nigerian" },
  { code: "NOR", name: "Noruega", nameEn: "Norway", nationality: "Noruega", nationalityEn: "Norwegian" },
  { code: "NZL", name: "Nueva Zelanda", nameEn: "New Zealand", nationality: "Neozelandesa", nationalityEn: "New Zealander" },
  { code: "OMN", name: "Omán", nameEn: "Oman", nationality: "Omaní", nationalityEn: "Omani" },
  { code: "NLD", name: "Países Bajos", nameEn: "Netherlands", nationality: "Neerlandesa", nationalityEn: "Dutch" },
  { code: "PAK", name: "Pakistán", nameEn: "Pakistan", nationality: "Pakistaní", nationalityEn: "Pakistani" },
  { code: "PLW", name: "Palaos", nameEn: "Palau", nationality: "Palauana", nationalityEn: "Palauan" },
  { code: "PSE", name: "Palestina", nameEn: "Palestine", nationality: "Palestina", nationalityEn: "Palestinian" },
  { code: "PAN", name: "Panamá", nameEn: "Panama", nationality: "Panameña", nationalityEn: "Panamanian" },
  { code: "PNG", name: "Papúa Nueva Guinea", nameEn: "Papua New Guinea", nationality: "Papú", nationalityEn: "Papua New Guinean" },
  { code: "PRY", name: "Paraguay", nameEn: "Paraguay", nationality: "Paraguaya", nationalityEn: "Paraguayan" },
  { code: "PER", name: "Perú", nameEn: "Peru", nationality: "Peruana", nationalityEn: "Peruvian" },
  { code: "POL", name: "Polonia", nameEn: "Poland", nationality: "Polaca", nationalityEn: "Polish" },
  { code: "PRT", name: "Portugal", nameEn: "Portugal", nationality: "Portuguesa", nationalityEn: "Portuguese" },
  { code: "GBR", name: "Reino Unido", nameEn: "United Kingdom", nationality: "Británica", nationalityEn: "British" },
  { code: "CAF", name: "República Centroafricana", nameEn: "Central African Republic", nationality: "Centroafricana", nationalityEn: "Central African" },
  { code: "CZE", name: "República Checa", nameEn: "Czech Republic", nationality: "Checa", nationalityEn: "Czech" },
  { code: "COD", name: "República Democrática del Congo", nameEn: "Democratic Republic of the Congo", nationality: "Congoleña", nationalityEn: "Congolese" },
  { code: "DOM", name: "República Dominicana", nameEn: "Dominican Republic", nationality: "Dominicana", nationalityEn: "Dominican" },
  { code: "RWA", name: "Ruanda", nameEn: "Rwanda", nationality: "Ruandesa", nationalityEn: "Rwandan" },
  { code: "ROU", name: "Rumanía", nameEn: "Romania", nationality: "Rumana", nationalityEn: "Romanian" },
  { code: "RUS", name: "Rusia", nameEn: "Russia", nationality: "Rusa", nationalityEn: "Russian" },
  { code: "WSM", name: "Samoa", nameEn: "Samoa", nationality: "Samoana", nationalityEn: "Samoan" },
  { code: "SMR", name: "San Marino", nameEn: "San Marino", nationality: "Sanmarinense", nationalityEn: "Sammarinese" },
  { code: "VCT", name: "San Vicente y las Granadinas", nameEn: "Saint Vincent and the Grenadines", nationality: "Sanvicentina", nationalityEn: "Saint Vincentian" },
  { code: "LCA", name: "Santa Lucía", nameEn: "Saint Lucia", nationality: "Santalucense", nationalityEn: "Saint Lucian" },
  { code: "STP", name: "Santo Tomé y Príncipe", nameEn: "Sao Tome and Principe", nationality: "Santotomense", nationalityEn: "Sao Tomean" },
  { code: "SEN", name: "Senegal", nameEn: "Senegal", nationality: "Senegalesa", nationalityEn: "Senegalese" },
  { code: "SRB", name: "Serbia", nameEn: "Serbia", nationality: "Serbia", nationalityEn: "Serbian" },
  { code: "SYC", name: "Seychelles", nameEn: "Seychelles", nationality: "Seychellense", nationalityEn: "Seychellois" },
  { code: "SLE", name: "Sierra Leona", nameEn: "Sierra Leone", nationality: "Sierraleonesa", nationalityEn: "Sierra Leonean" },
  { code: "SGP", name: "Singapur", nameEn: "Singapore", nationality: "Singapurense", nationalityEn: "Singaporean" },
  { code: "SYR", name: "Siria", nameEn: "Syria", nationality: "Siria", nationalityEn: "Syrian" },
  { code: "SOM", name: "Somalia", nameEn: "Somalia", nationality: "Somalí", nationalityEn: "Somali" },
  { code: "LKA", name: "Sri Lanka", nameEn: "Sri Lanka", nationality: "Ceilanesa", nationalityEn: "Sri Lankan" },
  { code: "ZAF", name: "Sudáfrica", nameEn: "South Africa", nationality: "Sudafricana", nationalityEn: "South African" },
  { code: "SDN", name: "Sudán", nameEn: "Sudan", nationality: "Sudanesa", nationalityEn: "Sudanese" },
  { code: "SSD", name: "Sudán del Sur", nameEn: "South Sudan", nationality: "Sursudanesa", nationalityEn: "South Sudanese" },
  { code: "SWE", name: "Suecia", nameEn: "Sweden", nationality: "Sueca", nationalityEn: "Swedish" },
  { code: "CHE", name: "Suiza", nameEn: "Switzerland", nationality: "Suiza", nationalityEn: "Swiss" },
  { code: "SUR", name: "Surinam", nameEn: "Suriname", nationality: "Surinamesa", nationalityEn: "Surinamese" },
  { code: "THA", name: "Tailandia", nameEn: "Thailand", nationality: "Tailandesa", nationalityEn: "Thai" },
  { code: "TWN", name: "Taiwán", nameEn: "Taiwan", nationality: "Taiwanesa", nationalityEn: "Taiwanese" },
  { code: "TZA", name: "Tanzania", nameEn: "Tanzania", nationality: "Tanzana", nationalityEn: "Tanzanian" },
  { code: "TJK", name: "Tayikistán", nameEn: "Tajikistan", nationality: "Tayika", nationalityEn: "Tajikistani" },
  { code: "TLS", name: "Timor Oriental", nameEn: "East Timor", nationality: "Timorense", nationalityEn: "Timorese" },
  { code: "TGO", name: "Togo", nameEn: "Togo", nationality: "Togolesa", nationalityEn: "Togolese" },
  { code: "TON", name: "Tonga", nameEn: "Tonga", nationality: "Tongana", nationalityEn: "Tongan" },
  { code: "TTO", name: "Trinidad y Tobago", nameEn: "Trinidad and Tobago", nationality: "Trinitense", nationalityEn: "Trinidadian" },
  { code: "TUN", name: "Túnez", nameEn: "Tunisia", nationality: "Tunecina", nationalityEn: "Tunisian" },
  { code: "TKM", name: "Turkmenistán", nameEn: "Turkmenistan", nationality: "Turcomana", nationalityEn: "Turkmen" },
  { code: "TUR", name: "Turquía", nameEn: "Turkey", nationality: "Turca", nationalityEn: "Turkish" },
  { code: "TUV", name: "Tuvalu", nameEn: "Tuvalu", nationality: "Tuvaluana", nationalityEn: "Tuvaluan" },
  { code: "UKR", name: "Ucrania", nameEn: "Ukraine", nationality: "Ucraniana", nationalityEn: "Ukrainian" },
  { code: "UGA", name: "Uganda", nameEn: "Uganda", nationality: "Ugandesa", nationalityEn: "Ugandan" },
  { code: "URY", name: "Uruguay", nameEn: "Uruguay", nationality: "Uruguaya", nationalityEn: "Uruguayan" },
  { code: "UZB", name: "Uzbekistán", nameEn: "Uzbekistan", nationality: "Uzbeka", nationalityEn: "Uzbekistani" },
  { code: "VUT", name: "Vanuatu", nameEn: "Vanuatu", nationality: "Vanuatuense", nationalityEn: "Ni-Vanuatu" },
  { code: "VAT", name: "Ciudad del Vaticano", nameEn: "Vatican City", nationality: "Vaticana", nationalityEn: "Vatican" },
  { code: "VEN", name: "Venezuela", nameEn: "Venezuela", nationality: "Venezolana", nationalityEn: "Venezuelan" },
  { code: "VNM", name: "Vietnam", nameEn: "Vietnam", nationality: "Vietnamita", nationalityEn: "Vietnamese" },
  { code: "YEM", name: "Yemen", nameEn: "Yemen", nationality: "Yemení", nationalityEn: "Yemeni" },
  { code: "DJI", name: "Yibuti", nameEn: "Djibouti", nationality: "Yibutiana", nationalityEn: "Djiboutian" },
  { code: "ZMB", name: "Zambia", nameEn: "Zambia", nationality: "Zambiana", nationalityEn: "Zambian" },
  { code: "ZWE", name: "Zimbabue", nameEn: "Zimbabwe", nationality: "Zimbabuense", nationalityEn: "Zimbabwean" },
];

export const getCountryName = (code: string, lang: "es" | "en" = "es") => {
  const country = COUNTRIES.find(c => c.code === code);
  return country ? (lang === "es" ? country.name : country.nameEn) : code;
};

export const getNationality = (code: string, lang: "es" | "en" = "es") => {
  const country = COUNTRIES.find(c => c.code === code);
  return country ? (lang === "es" ? country.nationality : country.nationalityEn) : code;
};
